<a href="https://colab.research.google.com/github/katairothomas/katairo/blob/master/Copy_of_My_first_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# My first Notebook

## Code cell

In [ ]:
print("Hello Katairo")

Hello Katairo

In [ ]:
foo = 42

In [ ]:
foo = 42 + 1
foo

43

## Text cell

This is my first cell. **I will make this bold**. *And I will make this Italic*

#I want to have different layers of the text
##This should be smaller
###This should be smallerer
####This should be smallest

## Some extra coding

### 4 loop

In [ ]:
for i in range(5):
    print(i)
#

0
1
2
3
4

### Run a function

In [ ]:
def greet(name):
  print(f"Hello {name}!")

greet("Katairo")

Hello Katairo!

##Install packages

In [1]:
import numpy as np  ##Numpy was already installed in Google collab

In [2]:
!pip install -q malariagen_data  ## Special code cell begins with an !

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 37.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.2/91.2 kB 3.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 252.9/252.9 kB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 64.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.7/71.7 kB 2.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 54.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 775.9/775.9 kB 13.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.8/47.8 kB 1.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 56.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.8/25.8 MB 34.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 50.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.3/211.3 kB 10.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 72.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 56.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 30.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.3/87.3 kB 3.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.7/101.7 kB 3.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 228.0/228.0 kB 8.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.3/43.3 kB 1.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.3/14.3 MB 20.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 36.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.0/88.0 kB 2.9 MB/s eta 0:00:00
  Building wheel for dash-cytoscape (setup.py) ... done
  Building wheel for asciitree (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.3.2 which is incompatible.

In [3]:
import malariagen_data

In [5]:
ag3 = malariagen_data.Ag3()
ag3

ColabLocationError:  Your Google Colab VM is not located in the US. Please select "Runtime
> Disconnect and delete runtime" from the menu to request a new VM,
then rerun your notebook.

Want to check if malariagen package is installed

In [ ]:
import sys

In [ ]:
"malariagen_data" in sys.modules

True

In [ ]:
!pip list

Package                                  Version
---------------------------------------- ------------------
absl-py                                  1.4.0
accelerate                               1.13.0
access                                   1.1.10.post3
affine                                   2.4.0
aiobotocore                              2.26.0
aiofiles                                 24.1.0
aiohappyeyeballs                         2.6.1
aiohttp                                  3.13.5
aioitertools                             0.13.0
aiosignal                                1.4.0
aiosqlite                                0.22.1
alabaster                                1.0.0
albucore                                 0.0.24
albumentations                           2.0.8
ale-py                                   0.11.2
alembic                                  1.18.4
altair                                   5.5.0
anjl                                     1.4.0
annotated-doc                            0.0.4
annotated-types                          0.7.0
antlr4-python3-runtime                   4.9.3
anyio                                    4.13.0
anywidget                                0.9.21
apsw                                     3.53.0.0
apswutils                                0.1.2
argon2-cffi                              25.1.0
argon2-cffi-bindings                     25.1.0
array_record                             0.8.3
arrow                                    1.4.0
arviz                                    0.22.0
asciitree                                0.3.3
astropy                                  7.2.0
astropy-iers-data                        0.2026.4.6.0.54.57
astunparse                               1.6.3
atpublic                                 5.1
attrs                                    26.1.0
audioread                                3.1.0
Authlib                                  1.6.9
autograd                                 1.8.0
babel                                    2.18.0
backcall                                 0.2.0
beartype                                 0.22.9
beautifulsoup4                           4.13.5
bed-reader                               1.0.6
betterproto                              2.0.0b6
bigframes                                2.39.0
bigquery-magics                          0.12.2
biopython                                1.87
bleach                                   6.3.0
blinker                                  1.9.0
blis                                     1.3.3
blobfile                                 3.2.0
blosc2                                   4.1.2
bokeh                                    3.8.2
botocore                                 1.41.5
Bottleneck                               1.4.2
bqplot                                   0.12.45
branca                                   0.8.2
brotli                                   1.2.0
CacheControl                             0.14.4
cachetools                               4.2.0
catalogue                                2.0.10
certifi                                  2026.2.25
cffi                                     2.0.0
chardet                                  5.2.0
charset-normalizer                       3.4.7
clarabel                                 0.11.1
click                                    8.3.2
click-plugins                            1.1.1.2
cligj                                    0.7.2
cloudpathlib                             0.23.0
cloudpickle                              3.1.2
cmake                                    3.31.10
cmdstanpy                                1.3.0
colorcet                                 3.1.0
colorlover                               0.3.0
community                                1.0.0b1
confection                               1.3.3
cons                                     0.4.7
contourpy                                1.3.3
cramjam                                  2.11.0
cryptography                             43.0.3
cufflinks                                0.17.3
curl_cffi                                0.15.0
cvxopt                                   1.3.2
cvxpy                                    1.6.7
cycler                                   0.12.1
cyipopt                                  1.5.0
cymem                                    2.0.13
Cython                                   3.0.12
dash                                     2.18.2
dash-core-components                     2.0.0
dash_cytoscape                           1.0.2
dash-html-components                     2.0.0
dash-table                               5.0.0
dask                                     2026.3.0
dataproc-spark-connect                   1.1.0
datasets                                 4.0.0
db-dtypes                                1.5.1
dbus-python                              1.2.18
debugpy                                  1.8.15
decorator                                4.4.2
defusedxml                               0.7.1
Deprecated                               1.3.1
deprecation                              2.1.0
diffusers                                0.37.1
dill                                     0.3.8
distributed                              2026.3.0
distro                                   1.9.0
dlib                                     19.24.6
dm-tree                                  0.1.10
docstring_parser                         0.17.0
docutils                                 0.21.2
dopamine_rl                              4.1.2
duckdb                                   1.3.2
earthengine-api                          1.7.21
easydict                                 1.13
editdistance                             0.8.1
eerepr                                   0.1.2
einops                                   0.8.2
en_core_web_sm                           3.8.0
entrypoints                              0.4
esda                                     2.9.0
et_xmlfile                               2.0.0
etils                                    1.14.0
etuples                                  0.3.10
Farama-Notifications                     0.0.4
fastai                                   2.8.7
fastapi                                  0.135.3
fastcore                                 1.12.36
fastdownload                             0.0.7
fasteners                                0.20
fastjsonschema                           2.21.2
fastlite                                 0.2.4
fastprogress                             1.1.5
fasttransform                            0.0.2
ffmpy                                    1.0.0
filelock                                 3.25.2
fiona                                    1.10.1
firebase-admin                           6.9.0
Flask                                    3.0.3
flatbuffers                              25.12.19
flax                                     0.11.2
folium                                   0.20.0
fonttools                                4.62.1
fqdn                                     1.5.1
frozendict                               2.4.7
frozenlist                               1.8.0
fsspec                                   2025.3.0
future                                   1.0.0
gast                                     0.7.0
gcsfs                                    2025.3.0
GDAL                                     3.8.4
gdown                                    5.2.1
geemap                                   0.37.2
geocoder                                 1.38.1
geographiclib                            2.1
geopandas                                1.1.3
geopy                                    2.4.1
giddy                                    2.3.6
gin-config                               0.5.0
gitdb                                    4.0.12
GitPython                                3.1.46
glob2                                    0.7
google                                   3.0.0
google-adk                               1.29.0
google-ai-generativelanguage             0.6.15
google-api-core                          2.30.3
google-api-python-client                 2.194.0
google-auth                              2.47.0
google-auth-httplib2                     0.3.1
google-auth-oauthlib                     1.3.1
google-cloud-aiplatform                  1.147.0
google-cloud-appengine-logging           1.9.0
google-cloud-audit-log                   0.5.0
google-cloud-bigquery                    3.41.0
google-cloud-bigquery-connection         1.21.0
google-cloud-bigquery-storage            2.37.0
google-cloud-bigtable                    2.36.0
google-cloud-core                        2.5.1
google-cloud-dataplex                    2.18.0
google-cloud-dataproc                    5.26.0
google-cloud-datastore                   2.24.0
google-cloud-discoveryengine             0.13.12
google-cloud-firestore                   2.26.0
google-cloud-functions                   1.23.0
google-cloud-iam                         2.22.0
google-cloud-language                    2.20.0
google-cloud-logging                     3.15.0
google-cloud-monitoring                  2.30.0
google-cloud-pubsub                      2.37.0
google-cloud-resource-manager            1.17.0
google-cloud-secret-manager              2.27.0
google-cloud-spanner                     3.64.0
google-cloud-speech                      2.38.0
google-cloud-storage                     3.10.1
google-cloud-trace                       1.19.0
google-cloud-translate                   3.26.0
google-colab                             1.0.0
google-crc32c                            1.8.0
google-genai                             1.68.0
google-generativeai                      0.8.6
google-pasta                             0.2.0
google-resumable-media                   2.8.2
googleapis-common-protos                 1.74.0
googledrivedownloader                    1.1.0
gradio                                   5.50.0
gradio_client                            1.14.0
grain                                    0.2.16
graphviz                                 0.21
greenlet                                 3.4.0
groovy                                   0.1.2
grpc-google-iam-v1                       0.14.4
grpc-interceptor                         0.15.4
grpcio                                   1.80.0
grpcio-status                            1.71.2
grpclib                                  0.4.9
gspread                                  6.2.1
gspread-dataframe                        4.0.0
gym                                      0.25.2
gym-notices                              0.1.0
gymnasium                                1.2.3
h11                                      0.16.0
h2                                       4.3.0
h5netcdf                                 1.8.1
h5py                                     3.16.0
hdbscan                                  0.8.42
hf-xet                                   1.4.3
highspy                                  1.14.0
holidays                                 0.94
holoviews                                1.22.1
hpack                                    4.1.0
html5lib                                 1.1
httpcore                                 1.0.9
httpimport                               1.4.1
httplib2                                 0.31.2
httptools                                0.7.1
httpx                                    0.28.1
httpx-sse                                0.4.3
huggingface_hub                          1.10.1
humanize                                 4.15.0
hyperframe                               6.1.0
hyperopt                                 0.2.7
ibis-framework                           9.5.0
idna                                     3.11
igv-notebook                             0.6.2
ImageIO                                  2.37.3
imageio-ffmpeg                           0.6.0
imagesize                                2.0.0
imbalanced-learn                         0.14.1
immutabledict                            4.3.1
importlib_metadata                       8.7.1
importlib_resources                      6.5.2
imutils                                  0.5.4
inequality                               1.1.2
inflect                                  7.5.0
iniconfig                                2.3.0
intel-cmplr-lib-ur                       2025.3.3
intel-openmp                             2025.3.3
ipinfo                                   5.5.0
ipyevents                                2.0.4
ipyfilechooser                           0.6.0
ipykernel                                6.17.1
ipyleaflet                               0.20.0
ipyparallel                              8.8.0
ipython                                  7.34.0
ipython-genutils                         0.2.0
ipython-sql                              0.5.0
ipywidgets                               7.7.1
isoduration                              20.11.0
itsdangerous                             2.2.0
jaraco.classes                           3.4.0
jaraco.context                           6.1.2
jaraco.functools                         4.4.0
jax                                      0.7.2
jaxlib                                   0.7.2
jedi                                     0.19.2
jeepney                                  0.9.0
jieba                                    0.42.1
Jinja2                                   3.1.6
jiter                                    0.14.0
jmespath                                 1.1.0
joblib                                   1.5.3
jsonpatch                                1.33
jsonpickle                               4.1.1
jsonpointer                              3.1.1
jsonschema                               4.26.0
jsonschema-specifications                2025.9.1
jupyter_client                           7.4.9
jupyter-console                          6.6.3
jupyter_core                             5.9.1
jupyter-events                           0.12.0
jupyter_kernel_gateway                   2.5.2
jupyter-leaflet                          0.20.0
jupyter_server                           2.14.0
jupyter_server_terminals                 0.5.4
jupyterlab_pygments                      0.3.0
jupyterlab_widgets                       3.0.16
jupytext                                 1.19.1
kaggle                                   2.0.1
kagglehub                                1.0.0
kagglesdk                                0.1.18
keras                                    3.13.2
keras-hub                                0.26.0
keras-nlp                                0.26.0
keyring                                  25.7.0
keyrings.google-artifactregistry-auth    1.1.2
kiwisolver                               1.5.0
langchain                                1.2.15
langchain-core                           1.2.28
langgraph                                1.1.6
langgraph-checkpoint                     4.0.1
langgraph-prebuilt                       1.0.9
langgraph-sdk                            0.3.13
langsmith                                0.7.30
lark                                     1.3.1
launchpadlib                             1.10.16
lazr.restfulclient                       0.14.4
lazr.uri                                 1.0.6
lazy-loader                              0.5
libclang                                 18.1.1
libpysal                                 4.14.1
librosa                                  0.11.0
lightgbm                                 4.6.0
linkify-it-py                            2.1.0
llvmlite                                 0.43.0
locket                                   1.0.0
logical-unification                      0.4.7
lxml                                     6.0.3
Mako                                     1.3.10
malariagen_data                          15.7.0
mapclassify                              2.10.0
Markdown                                 3.10.2
markdown-it-py                           4.0.0
MarkupSafe                               3.0.3
matplotlib                               3.10.0
matplotlib-inline                        0.2.1
matplotlib-venn                          1.1.2
mcp                                      1.27.0
mdit-py-plugins                          0.5.0
mdurl                                    0.1.2
mgwr                                     2.2.1
miniKanren                               1.0.5
missingno                                0.5.2
mistune                                  3.2.0
mizani                                   0.13.5
mkl                                      2025.3.1
ml_dtypes                                0.5.4
mlxtend                                  0.23.4
mmh3                                     5.2.1
momepy                                   0.11.0
more-itertools                           10.8.0
moviepy                                  1.0.3
mpmath                                   1.3.0
msgpack                                  1.1.2
multidict                                6.7.1
multipledispatch                         1.0.0
multiprocess                             0.70.16
multitasking                             0.0.12
murmurhash                               1.0.15
music21                                  9.9.1
namex                                    0.1.0
narwhals                                 2.19.0
natsort                                  8.4.0
nbclassic                                1.3.3
nbclient                                 0.10.4
nbconvert                                7.17.1
nbformat                                 5.10.4
ndindex                                  1.10.1
nest-asyncio                             1.6.0
networkx                                 3.6.1
nibabel                                  5.4.2
nltk                                     3.9.1
notebook                                 6.5.7
notebook_shim                            0.2.4
numba                                    0.60.0
numcodecs                                0.15.1
numexpr                                  2.14.1
numpy                                    2.0.2
numpydoc_decorator                       2.2.1
nvidia-nccl-cu12                         2.29.7
oauth2client                             4.1.3
oauthlib                                 3.3.1
omegaconf                                2.3.0
onemkl-license                           2025.3.1
openai                                   2.31.0
opencv-contrib-python                    4.13.0.92
opencv-python                            4.13.0.92
opencv-python-headless                   4.13.0.92
openpyxl                                 3.1.5
opentelemetry-api                        1.38.0
opentelemetry-exporter-gcp-logging       1.11.0a0
opentelemetry-exporter-gcp-monitoring    1.11.0a0
opentelemetry-exporter-gcp-trace         1.11.0
opentelemetry-exporter-otlp-proto-common 1.38.0
opentelemetry-exporter-otlp-proto-http   1.38.0
opentelemetry-proto                      1.38.0
opentelemetry-resourcedetector-gcp       1.11.0a0
opentelemetry-sdk                        1.38.0
opentelemetry-semantic-conventions       0.59b0
opt_einsum                               3.4.0
optax                                    0.2.8
optree                                   0.19.0
orbax-checkpoint                         0.11.34
orjson                                   3.11.8
ormsgpack                                1.12.2
osqp                                     1.1.1
overrides                                7.7.0
packaging                                26.0
pandas                                   2.3.2
pandas-datareader                        0.10.0
pandas-gbq                               0.30.0
pandas-stubs                             2.2.2.240909
pandocfilters                            1.5.1
panel                                    1.8.10
param                                    2.3.3
parso                                    0.8.6

In [ ]:
ag3 = malariagen_data.Ag3()

PermissionError:
Your Google account does not appear to have permission to access the data.
If you have not yet submitted a data access request, please complete the form
at the following link: https://forms.gle/d1NV3aL3EoVQGSHYA

If you are still experiencing problems accessing data, please email
support@malariagen.net for assistance.

## Plotting

In [ ]:
x = np.random.binomial(n=30, p=0.5, size=10_000) ##Simulate flipping a fair coin 30 times, repeat that experiment 10,000 times, and record how many heads you get each time
x

array([20, 14, 19, ..., 17, 17, 14])

In [ ]:
import plotly.express as px

In [ ]:
fig1 = px.histogram(
    x=x,
    title= " Histogram of randomly generated binomial data",
    labels={'x': "Number of Heads", 'y': "Frequency"},
    nbins=30)
fig1.show()

# **Using the Ag3 dataset**

In [1]:
!pip install -q malariagen_data

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 19.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.2/91.2 kB 5.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 252.9/252.9 kB 15.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 65.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.7/71.7 kB 4.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 56.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 775.9/775.9 kB 31.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.8/47.8 kB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 91.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.8/25.8 MB 43.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 67.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.3/211.3 kB 14.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 83.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 54.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 50.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.3/87.3 kB 6.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.7/101.7 kB 6.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 228.0/228.0 kB 16.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.3/43.3 kB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.3/14.3 MB 21.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 57.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.0/88.0 kB 6.2 MB/s eta 0:00:00
  Building wheel for dash-cytoscape (setup.py) ... done
  Building wheel for asciitree (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.3.2 which is incompatible.

In [2]:
import malariagen_data

In [3]:
ag3 = malariagen_data.Ag3()
ag3

<MalariaGEN Ag3 API client>
Storage URL                           : gs://vo_agam_release_master_us_central1/
Data releases available               : 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 3.10, 3.11, 3.12, 3.13, 3.14, 3.15, 3.16
Results cache                         : None
Cohorts analysis                      : 20260120
AIM analysis                          : 20220528
Site filters analysis                 : dt_20200416
Software version                      : malariagen_data 15.7.0
Client location                       : South Carolina, United States (Google Cloud us-east1)
Data filtered to unrestricted use only: False
Data filtered to surveillance use only: False
Relevant data releases                : 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 3.10, 3.11, 3.12, 3.13, 3.14, 3.15, 3.16
---
Please note that data are subject to terms of use,
for more information see https://www.malariagen.net/data
or contact support@malariagen.net. For API documentation see
https://malariagen.github.io/malariagen-data-python/v15.7.0/Ag3.html

# Loading Sample metada

In [4]:
df_samples = ag3.sample_metadata(sample_sets="3.0")
df_samples

,sample_id,partner_sample_id,contributor,country,location,year,month,latitude,longitude,sex_call,...,admin1_name,admin1_iso,admin2_name,taxon,cohort_admin1_year,cohort_admin1_month,cohort_admin1_quarter,cohort_admin2_year,cohort_admin2_month,cohort_admin2_quarter
0,AR0047-C,LUA047,Joao Pinto,Angola,Luanda-A,2009,4,-8.884,13.302,F,...,Luanda,AO-LUA,Luanda,coluzzii,AO-LUA_colu_2009,AO-LUA_colu_2009_04,AO-LUA_colu_2009_Q2,AO-LUA_Luanda_colu_2009,AO-LUA_Luanda_colu_2009_04,AO-LUA_Luanda_colu_2009_Q2
1,AR0049-C,LUA049,Joao Pinto,Angola,Luanda-A,2009,4,-8.884,13.302,F,...,Luanda,AO-LUA,Luanda,coluzzii,AO-LUA_colu_2009,AO-LUA_colu_2009_04,AO-LUA_colu_2009_Q2,AO-LUA_Luanda_colu_2009,AO-LUA_Luanda_colu_2009_04,AO-LUA_Luanda_colu_2009_Q2
2,AR0051-C,LUA051,Joao Pinto,Angola,Luanda-A,2009,4,-8.884,13.302,F,...,Luanda,AO-LUA,Luanda,coluzzii,AO-LUA_colu_2009,AO-LUA_colu_2009_04,AO-LUA_colu_2009_Q2,AO-LUA_Luanda_colu_2009,AO-LUA_Luanda_colu_2009_04,AO-LUA_Luanda_colu_2009_Q2
3,AR0061-C,LUA061,Joao Pinto,Angola,Luanda-A,2009,4,-8.884,13.302,F,...,Luanda,AO-LUA,Luanda,coluzzii,AO-LUA_colu_2009,AO-LUA_colu_2009_04,AO-LUA_colu_2009_Q2,AO-LUA_Luanda_colu_2009,AO-LUA_Luanda_colu_2009_04,AO-LUA_Luanda_colu_2009_Q2
4,AR0078-C,LUA078,Joao Pinto,Angola,Luanda-A,2009,4,-8.884,13.302,F,...,Luanda,AO-LUA,Luanda,coluzzii,AO-LUA_colu_2009,AO-LUA_colu_2009_04,AO-LUA_colu_2009_Q2,AO-LUA_Luanda_colu_2009,AO-LUA_Luanda_colu_2009_04,AO-LUA_Luanda_colu_2009_Q2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3076,AD0494-C,80-2-o-16,Martin Donnelly,Lab Cross,LSTM,-1,-1,53.409,-2.969,F,...,NaN,NaN,NaN,unassigned,NaN,NaN,NaN,NaN,NaN,NaN
3077,AD0495-C,80-2-o-17,Martin Donnelly,Lab Cross,LSTM,-1,-1,53.409,-2.969,M,...,NaN,NaN,NaN,unassigned,NaN,NaN,NaN,NaN,NaN,NaN
3078,AD0496-C,80-2-o-18,Martin Donnelly,Lab Cross,LSTM,-1,-1,53.409,-2.969,M,...,NaN,NaN,NaN,unassigned,NaN,NaN,NaN,NaN,NaN,NaN
3079,AD0497-C,80-2-o-19,Martin Donnelly,Lab Cross,LSTM,-1,-1,53.409,-2.969,F,...,NaN,NaN,NaN,unassigned,NaN,NaN,NaN,NaN,NaN,NaN
3080,AD0498-C,80-2-o-20,Martin Donnelly,Lab Cross,LSTM,-1,-1,53.409,-2.969,M,...,NaN,NaN,NaN,unassigned,NaN,NaN,NaN,NaN,NaN,NaN

# Explore sample metadata

In [ ]:
df_samples.groupby("country").size()

country
Angola                               81
Burkina Faso                        296
Cameroon                            444
Central African Republic             73
Cote d'Ivoire                        80
Democratic Republic of the Congo     76
Equatorial Guinea                    10
Gabon                                69
Gambia, The                         279
Ghana                               100
Guinea                              136
Guinea-Bissau                       101
Kenya                                86
Lab Cross                           297
Malawi                               41
Mali                                225
Mayotte                              23
Mozambique                           74
Tanzania                            300
Uganda                              290
dtype: int64

In [ ]:
df_samples.query("country == 'Burkina Faso'")

,sample_id,partner_sample_id,contributor,country,location,year,month,latitude,longitude,sex_call,...,admin1_name,admin1_iso,admin2_name,taxon,cohort_admin1_year,cohort_admin1_month,cohort_admin1_quarter,cohort_admin2_year,cohort_admin2_month,cohort_admin2_quarter
81,AB0085-Cx,BF2-4,Austin Burt,Burkina Faso,Pala,2012,7,11.151,-4.235,F,...,Hauts-Bassins,BF-09,Houet,gambiae,BF-09_gamb_2012,BF-09_gamb_2012_07,BF-09_gamb_2012_Q3,BF-09_Houet_gamb_2012,BF-09_Houet_gamb_2012_07,BF-09_Houet_gamb_2012_Q3
82,AB0086-Cx,BF2-6,Austin Burt,Burkina Faso,Pala,2012,7,11.151,-4.235,F,...,Hauts-Bassins,BF-09,Houet,gambiae,BF-09_gamb_2012,BF-09_gamb_2012_07,BF-09_gamb_2012_Q3,BF-09_Houet_gamb_2012,BF-09_Houet_gamb_2012_07,BF-09_Houet_gamb_2012_Q3
83,AB0087-C,BF3-3,Austin Burt,Burkina Faso,Bana,2012,7,11.233,-4.472,F,...,Hauts-Bassins,BF-09,Houet,coluzzii,BF-09_colu_2012,BF-09_colu_2012_07,BF-09_colu_2012_Q3,BF-09_Houet_colu_2012,BF-09_Houet_colu_2012_07,BF-09_Houet_colu_2012_Q3
84,AB0088-C,BF3-5,Austin Burt,Burkina Faso,Bana,2012,7,11.233,-4.472,F,...,Hauts-Bassins,BF-09,Houet,coluzzii,BF-09_colu_2012,BF-09_colu_2012_07,BF-09_colu_2012_Q3,BF-09_Houet_colu_2012,BF-09_Houet_colu_2012_07,BF-09_Houet_colu_2012_Q3
85,AB0089-Cx,BF3-8,Austin Burt,Burkina Faso,Bana,2012,7,11.233,-4.472,F,...,Hauts-Bassins,BF-09,Houet,coluzzii,BF-09_colu_2012,BF-09_colu_2012_07,BF-09_colu_2012_Q3,BF-09_Houet_colu_2012,BF-09_Houet_colu_2012_07,BF-09_Houet_colu_2012_Q3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372,AB0314-C,6775,Nora Besansky,Burkina Faso,Monomtenga-A,2004,8,12.060,-1.170,F,...,Centre-Sud,BF-07,Bazega,gambiae,BF-07_gamb_2004,BF-07_gamb_2004_08,BF-07_gamb_2004_Q3,BF-07_Bazega_gamb_2004,BF-07_Bazega_gamb_2004_08,BF-07_Bazega_gamb_2004_Q3
373,AB0315-C,6777,Nora Besansky,Burkina Faso,Monomtenga-A,2004,8,12.060,-1.170,F,...,Centre-Sud,BF-07,Bazega,gambiae,BF-07_gamb_2004,BF-07_gamb_2004_08,BF-07_gamb_2004_Q3,BF-07_Bazega_gamb_2004,BF-07_Bazega_gamb_2004_08,BF-07_Bazega_gamb_2004_Q3
374,AB0316-C,6779,Nora Besansky,Burkina Faso,Monomtenga-A,2004,8,12.060,-1.170,F,...,Centre-Sud,BF-07,Bazega,gambiae,BF-07_gamb_2004,BF-07_gamb_2004_08,BF-07_gamb_2004_Q3,BF-07_Bazega_gamb_2004,BF-07_Bazega_gamb_2004_08,BF-07_Bazega_gamb_2004_Q3
375,AB0318-C,5072,Nora Besansky,Burkina Faso,Monomtenga-A,2004,7,12.060,-1.170,F,...,Centre-Sud,BF-07,Bazega,gambiae,BF-07_gamb_2004,BF-07_gamb_2004_07,BF-07_gamb_2004_Q3,BF-07_Bazega_gamb_2004,BF-07_Bazega_gamb_2004_07,BF-07_Bazega_gamb_2004_Q3
376,AB0325-C,1403,Nora Besansky,Burkina Faso,Monomtenga-A,2004,6,12.060,-1.170,F,...,Centre-Sud,BF-07,Bazega,gambiae,BF-07_gamb_2004,BF-07_gamb_2004_06,BF-07_gamb_2004_Q2,BF-07_Bazega_gamb_2004,BF-07_Bazega_gamb_2004_06,BF-07_Bazega_gamb_2004_Q2

In [ ]:
df_samples.query("country == 'Burkina Faso'").groupby("year").size()

year
2004     13
2012    181
2014    102
dtype: int64

In [ ]:
df_samples.query("country == 'Burkina Faso' and year == 2014")

,sample_id,partner_sample_id,contributor,country,location,year,month,latitude,longitude,sex_call,...,admin1_name,admin1_iso,admin2_name,taxon,cohort_admin1_year,cohort_admin1_month,cohort_admin1_quarter,cohort_admin2_year,cohort_admin2_month,cohort_admin2_quarter
262,AB0326-C,BF18-1,Austin Burt,Burkina Faso,Bana,2014,7,11.233,-4.472,F,...,Hauts-Bassins,BF-09,Houet,coluzzii,BF-09_colu_2014,BF-09_colu_2014_07,BF-09_colu_2014_Q3,BF-09_Houet_colu_2014,BF-09_Houet_colu_2014_07,BF-09_Houet_colu_2014_Q3
263,AB0327-C,BF18-3,Austin Burt,Burkina Faso,Bana,2014,7,11.233,-4.472,F,...,Hauts-Bassins,BF-09,Houet,coluzzii,BF-09_colu_2014,BF-09_colu_2014_07,BF-09_colu_2014_Q3,BF-09_Houet_colu_2014,BF-09_Houet_colu_2014_07,BF-09_Houet_colu_2014_Q3
264,AB0328-C,BF18-4,Austin Burt,Burkina Faso,Bana,2014,7,11.233,-4.472,F,...,Hauts-Bassins,BF-09,Houet,coluzzii,BF-09_colu_2014,BF-09_colu_2014_07,BF-09_colu_2014_Q3,BF-09_Houet_colu_2014,BF-09_Houet_colu_2014_07,BF-09_Houet_colu_2014_Q3
265,AB0329-C,BF18-5,Austin Burt,Burkina Faso,Bana,2014,7,11.233,-4.472,F,...,Hauts-Bassins,BF-09,Houet,coluzzii,BF-09_colu_2014,BF-09_colu_2014_07,BF-09_colu_2014_Q3,BF-09_Houet_colu_2014,BF-09_Houet_colu_2014_07,BF-09_Houet_colu_2014_Q3
266,AB0330-C,BF18-6,Austin Burt,Burkina Faso,Bana,2014,7,11.233,-4.472,F,...,Hauts-Bassins,BF-09,Houet,coluzzii,BF-09_colu_2014,BF-09_colu_2014_07,BF-09_colu_2014_Q3,BF-09_Houet_colu_2014,BF-09_Houet_colu_2014_07,BF-09_Houet_colu_2014_Q3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359,AB0533-C,BF13-18,Austin Burt,Burkina Faso,Souroukoudinga,2014,7,11.235,-4.535,F,...,Hauts-Bassins,BF-09,Houet,gambiae,BF-09_gamb_2014,BF-09_gamb_2014_07,BF-09_gamb_2014_Q3,BF-09_Houet_gamb_2014,BF-09_Houet_gamb_2014_07,BF-09_Houet_gamb_2014_Q3
360,AB0536-C,BF13-31,Austin Burt,Burkina Faso,Souroukoudinga,2014,7,11.235,-4.535,F,...,Hauts-Bassins,BF-09,Houet,gambiae,BF-09_gamb_2014,BF-09_gamb_2014_07,BF-09_gamb_2014_Q3,BF-09_Houet_gamb_2014,BF-09_Houet_gamb_2014_07,BF-09_Houet_gamb_2014_Q3
361,AB0537-C,BF13-32,Austin Burt,Burkina Faso,Souroukoudinga,2014,7,11.235,-4.535,F,...,Hauts-Bassins,BF-09,Houet,gambiae,BF-09_gamb_2014,BF-09_gamb_2014_07,BF-09_gamb_2014_Q3,BF-09_Houet_gamb_2014,BF-09_Houet_gamb_2014_07,BF-09_Houet_gamb_2014_Q3
362,AB0538-C,BF13-33,Austin Burt,Burkina Faso,Souroukoudinga,2014,7,11.235,-4.535,F,...,Hauts-Bassins,BF-09,Houet,gambiae,BF-09_gamb_2014,BF-09_gamb_2014_07,BF-09_gamb_2014_Q3,BF-09_Houet_gamb_2014,BF-09_Houet_gamb_2014_07,BF-09_Houet_gamb_2014_Q3
363,AB0408-C,BF14-20,Austin Burt,Burkina Faso,Bana,2014,7,11.233,-4.472,F,...,Hauts-Bassins,BF-09,Houet,coluzzii,BF-09_colu_2014,BF-09_colu_2014_07,BF-09_colu_2014_Q3,BF-09_Houet_colu_2014,BF-09_Houet_colu_2014_07,BF-09_Houet_colu_2014_Q3

In [ ]:
df_samples.query("country == 'Burkina Faso' and year == 2014").groupby("taxon").size()
#

taxon
arabiensis     3
coluzzii      53
gambiae       46
dtype: int64

## We are now going to use pivot tables

In [ ]:
pivot_country_year_taxon = (
    df_samples
    .pivot_table(
        index= ["country", "year"],
        columns="taxon",
        values="sample_id",
        aggfunc="count",
        fill_value=0
    )
    )
pivot_country_year_taxon

taxon                                   arabiensis  bissau  coluzzii  gambiae  \
country                          year
Angola                            2009           0       0        81        0
Burkina Faso                      2004           0       0         0       13
                                  2012           0       0        82       99
                                  2014           3       0        53       46
Cameroon                          2005           0       0         7       90
                                  2009           0       0         0      303
                                  2013           2       0        19       23
Central African Republic          1993           0       0         5        2
                                  1994           0       0        13       53
Cote d'Ivoire                     2012           0       0        80        0
Democratic Republic of the Congo  2015           0       0         0       76
Equatorial Guinea                 2002           0       0         0       10
Gabon                             2000           0       0         0       69
Gambia, The                       2006           0       9        22        0
                                  2011           0      68         6        0
                                  2012           0       0       172        2
Ghana                             2012           0       0        64       36
Guinea                            2012           0       0        11      125
Guinea-Bissau                     2010           0      93         0        8
Kenya                             2000           0       0         0       19
                                  2007           3       0         0        0
                                  2012          10       0         0        0
Lab Cross                        -1              0       0         0        0
Malawi                            2015          41       0         0        0
Mali                              2004           2       0        36       33
                                  2012           0       0        27       65
                                  2014           0       0        27       33
Mayotte                           2011           0       0         0       23
Mozambique                        2003           0       0         0        3
                                  2004           0       0         0       71
Tanzania                          2012          87       0         0        0
                                  2013           1       0         0       32
                                  2015         137       0         0       32
Uganda                            2012          82       0         0      207

taxon                                   pwani  unassigned
country                          year
Angola                            2009      0           0
Burkina Faso                      2004      0           0
                                  2012      0           0
                                  2014      0           0
Cameroon                          2005      0           0
                                  2009      0           0
                                  2013      0           0
Central African Republic          1993      0           0
                                  1994      0           0
Cote d'Ivoire                     2012      0           0
Democratic Republic of the Congo  2015      0           0
Equatorial Guinea                 2002      0           0
Gabon                             2000      0           0
Gambia, The                       2006      0           0
                                  2011      0           0
                                  2012      0           0
Ghana                             2012      0           0
Guinea                            2012      0           0
Guinea-Bissau                     2010      0           0
Kenya                             2000      0           0
                                  2007      0           0
                                  2012     54           0
Lab Cross                        -1         0         297
Malawi                            2015      0           0
Mali                              2004      0           0
                                  2012      0           2
                                  2014      0           0
Mayotte                           2011      0           0
Mozambique                        2003      0           0
                                  2004      0           0
Tanzania                          2012      0           0
                                  2013     10           0
                                  2015      1           0
Uganda                            2012      0           1

In [ ]:
pivot_location_year_taxon_bf = (
    df_samples
    .query("country == 'Burkina Faso'")
    .pivot_table(
        index= ["admin1_name", "admin2_name", "location", "year"],
        columns="taxon",
        values="sample_id",
        aggfunc="count",
        fill_value=0
    )
)
pivot_location_year_taxon_bf

taxon                                          arabiensis  coluzzii  gambiae
admin1_name   admin2_name location       year
Centre-Sud    Bazega      Monomtenga-A   2004           0         0       13
Hauts-Bassins Houet       Bana           2012           0        42       23
                                         2014           1        47       15
                          Pala           2012           0        11       48
                                         2014           2         0       16
                          Souroukoudinga 2012           0        29       28
                                         2014           0         6       15

# Plotting maps of sampling locations

In [ ]:
!pip install -q ipyleaflet

In [ ]:
from ipyleaflet import Map, Marker, basemaps, ScaleControl

In [ ]:
m = Map(
    basemap=basemaps.OpenStreetMap.Mapnik,
    center=[0, 20],
    zoom=3,
)
m

Map(center=[0, 20], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', 'zoom_out_text…

In [ ]:
pivot_location_taxon = (
    df_samples
    .pivot_table(
        index= ["country", "location", "latitude", "longitude"],
        columns="taxon",
        values="sample_id",
        aggfunc="count",
        fill_value=0
    )
)
pivot_location_taxon

taxon                                           arabiensis  bissau  coluzzii  \
country      location       latitude longitude
Angola       Luanda-A       -8.884    13.302             0       0        81
Burkina Faso Bana            11.233  -4.472              1       0        89
             Monomtenga-A    12.060  -1.170              0       0         0
             Pala            11.151  -4.235              2       0        11
             Souroukoudinga  11.235  -4.535              0       0        35
...                                                    ...     ...       ...
Tanzania     Muheza         -4.940    38.948             1       0         0
             Muleba-A       -1.962    31.651           137       0         0
             Tarime         -1.431    34.199            47       0         0
Uganda       Kihihi         -0.751    29.701             1       0         0
             Nagongera       0.770    34.026            81       0         0

taxon                                           gambiae  pwani  unassigned
country      location       latitude longitude
Angola       Luanda-A       -8.884    13.302          0      0           0
Burkina Faso Bana            11.233  -4.472          38      0           0
             Monomtenga-A    12.060  -1.170          13      0           0
             Pala            11.151  -4.235          64      0           0
             Souroukoudinga  11.235  -4.535          43      0           0
...                                                 ...    ...         ...
Tanzania     Muheza         -4.940    38.948         32     10           0
             Muleba-A       -1.962    31.651         32      1           0
             Tarime         -1.431    34.199          0      0           0
Uganda       Kihihi         -0.751    29.701         95      0           0
             Nagongera       0.770    34.026        112      0           1

[127 rows x 6 columns]

In [ ]:
m = Map(
    basemap=basemaps.OpenStreetMap.Mapnik,
    center=[0, 20],
    zoom=3,
)

#Use for loop to add sampling locations
for row in pivot_location_taxon.reset_index().itertuples():
  title = (
      f"{row.location}, {row.country} ({row.latitude:3f}.{row.longitude:3f})\n"
      f"{row.gambiae} gambiae, {row.coluzzii} coluzzi, ({row.arabiensis} arabiensis"
  )
  marker = Marker(
      location=(row.latitude, row.longitude),
      draggable=False,
      title=title,
  )
  m.add_layer(marker)

##Add scale bar
m.add_control(ScaleControl(position="bottomleft"))

##Display map
m

Map(center=[0, 20], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', 'zoom_out_text…

##Exercise from Training

###Number of mosquito specimens available for each different Anopheles species

In [6]:
df_samples.groupby("taxon").size()

taxon
arabiensis     368
bissau         170
coluzzii       705
gambiae       1473
pwani           65
unassigned     300
dtype: int64

### Number of samples available in the Ag3.0 resource that were collected in Mali, summarized by year, location and taxon

In [5]:
samples_Mali_year_location = \
df_samples \
.query("country == 'Mali'") \
.pivot_table(
    index=["year", "location", "country"],
    columns="taxon",
    values="sample_id",
    aggfunc="count"
)

samples_Mali_year_location

taxon                        arabiensis  coluzzii  gambiae  unassigned
year location       country
2004 Bancoumana     Mali            NaN       NaN      9.0         NaN
     Douna          Mali            1.0      19.0      NaN         NaN
     Fanzana        Mali            1.0       6.0      1.0         NaN
     Kela           Mali            NaN       NaN     23.0         NaN
     Moribobougou   Mali            NaN       7.0      NaN         NaN
     N'Gabakoro     Mali            NaN       4.0      NaN         NaN
2012 Takan          Mali            NaN      25.0      5.0         1.0
     Toumani Oulena Mali            NaN       2.0     60.0         1.0
2014 Kababougou     Mali            NaN      12.0     28.0         NaN
     Ouassorola     Mali            NaN       9.0      4.0         NaN
     Tieneguebougou Mali            NaN       6.0      1.0         NaN

### How many countries are there for which we have samples of A. coluzzii

In [15]:
countries_coluzzii = (
    df_samples
    .query("taxon == 'coluzzii'")
    .pivot_table(
        index="country",
        values="sample_id",
        aggfunc="count"
    )
)
countries_coluzzii

                          sample_id
country
Angola                           81
Burkina Faso                    135
Cameroon                         26
Central African Republic         18
Cote d'Ivoire                    80
Gambia, The                     200
Ghana                            64
Guinea                           11
Mali                             90